# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # ========== 核心修改1：窗口基础设置（适配动物识别） ==========
        MainWindow.setObjectName("MainWindow")
        # 调整窗口大小更舒展（原438×522 → 600×550），适配图片显示
        MainWindow.resize(600, 550)
        MainWindow.setMinimumSize(QtCore.QSize(600, 550))  # 固定最小尺寸，避免缩放变形

        # 中央控件
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # ========== 核心修改2：选择图片按钮（语义+布局优化） ==========
        self.chooseImgBtn = QtWidgets.QPushButton(self.centralwidget)
        # 调整按钮位置+大小，居中显示
        self.chooseImgBtn.setGeometry(QtCore.QRect(180, 40, 240, 60))
        self.chooseImgBtn.setObjectName("chooseImgBtn")
        # 按钮样式优化（可选，提升视觉效果）
        self.chooseImgBtn.setStyleSheet("font-size: 14px; font-weight: bold;")

        # ========== 核心修改3：图片显示标签（适配动物图片比例） ==========
        self.imgLab = QtWidgets.QLabel(self.centralwidget)
        # 调整位置+大小，更大更居中，适配常见图片比例
        self.imgLab.setGeometry(QtCore.QRect(80, 120, 440, 280))
        self.imgLab.setText("")
        # 新增：设置图片居中显示，添加边框（提升视觉）
        self.imgLab.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLab.setStyleSheet("border: 1px solid #cccccc;")
        self.imgLab.setObjectName("imgLab")

        # ========== 核心修改4：识别结果标签（解决重叠+语义优化） ==========
        # 提示标签（AI识别结果为 → 动物识别结果：）
        self.lab = QtWidgets.QLabel(self.centralwidget)
        # 调整位置，避免重叠
        self.lab.setGeometry(QtCore.QRect(100, 430, 180, 50))
        self.lab.setObjectName("lab")
        # 样式优化
        self.lab.setStyleSheet("font-size: 14px; color: #333333;")

        # 结果显示标签（单独排版，不重叠）
        self.resLab = QtWidgets.QLabel(self.centralwidget)
        # 调整位置，在提示标签右侧
        self.resLab.setGeometry(QtCore.QRect(280, 430, 200, 50))
        self.resLab.setObjectName("resLab")
        # 样式优化（突出结果）
        self.resLab.setStyleSheet("font-size: 16px; color: #e64340; font-weight: bold;")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # ========== 核心修改5：界面文本全量适配动物识别 ==========
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # 窗口标题：MainWindow → 动物识别系统
        MainWindow.setWindowTitle(_translate("MainWindow", "动物识别系统"))
        # 按钮文本：选择图片 → 选择待识别的动物图片
        self.chooseImgBtn.setText(_translate("MainWindow", "选择待识别的动物图片"))
        # 提示标签：AI识别的结果为： → 动物识别结果：
        self.lab.setText(_translate("MainWindow", "动物识别结果："))
        # 结果标签初始文本（新增，提示未识别）
        self.resLab.setText(_translate("MainWindow", "未识别"))


# 测试界面（可选，直接运行该文件可预览界面）
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())